config/routes.rb
Rails.application.routes.draw do
  root to: 'visitors#index'
  devise_for :users
  resources :users
  post 'create_user' => 'users#create', as: :create_user
  get 'user_activity' => 'user_logins#index', as: :user_activity
  resources :accounts, only: [:index, :show, :update, :create] do
    resources :account_transactions, controller: 'account_transactions'
  end
end

app/models/account.rb
class Account < ActiveRecord::Base
  has_many :account_transactions
  belongs_to :user

  validates :name, uniqueness: { scope: :user }

  def total
    account_transactions.sum(:value) || 0
  end

  def check_total_value
    CriticalValueMailer.notification(self).deliver if total <= critical_value && send_notifications
  end
end

app/models/account_transaction.rb
class AccountTransaction < ActiveRecord::Base
  belongs_to :category
  belongs_to :account
  after_create :check_account_total

  delegate :name, to: :category, prefix: true

  def check_account_total
    account.check_total_value
  end

  def self.create_from_xml(filename)
    file = File.open(filename, "rb")
    content = file.read
    ActiveRecord::Base.transaction do
      transaction = AccountTransaction.new
      transaction.from_xml(content) if content
      transaction.save
    end
  end

  private

  def build_response(result)
    result_msg = result ? 'OK' : 'FAIL'
    File.open("a2/message#{id}.txt", w) { |f| f.write("<response>\n <message>#{result_msg}</message></response>") }
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :account_transactions
end

app/models/user.rb
class User < ActiveRecord::Base
  enum role: [:user, :vip, :admin]
  after_initialize :set_default_role, if: :new_record?

  def set_default_role
    self.role ||= :user
  end

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :stalkable
  has_many :logins, class_name: 'UserLogin'
  has_many :accounts
end

app/models/user_login.rb
class UserLogin < ActiveRecord::Base
  belongs_to :User
end

app/controllers/account_transactions_controller.rb
class AccountTransactionsController < ApplicationController
  before_action :authenticate_user!

  def index
    transactions
    respond_to do |format|
      format.json { render json: @transactions, methods: :category_name }
    end
  end

  def create
    category = Category.find_or_create_by(name:
                                            params[:account_transaction][:category])
    @transaction = AccountTransaction.new(transaction_params.merge(
                                            account_id: params[:account_id], category: category))
    if @transaction.save
      redirect_to account,
                  notice: 'A transaction has been added to your account.'
    else
      redirect_to account,
                  notice: 'Your transaction has not been added, sorry :('
    end
  end

  private

  def account
    @account ||= user.accounts.find(params[:account_id])
  end

  def user
    current_user
  end

  def transactions
    @transactions = account.account_transactions
    @transactions = @transactions.where(transaction_date: Date.strptime(params[:date_from], '%m/%d/%Y')..Date.strptime(params[:date_to], '%m/%d/%Y')) if params[:date_to].present? && params[:date_from].present?
  end

  def transaction_params
    params.require(:account_transaction).permit(:subject, :value, :purpose, :transaction_date, :category)
  end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :authenticate_user!

  def index
    accounts
    @account = Account.new
  end

  def create
    @account = Account.new(account_params.merge(user_id: current_user.id))
    @account.save
    redirect_to @account
  end

  def show
    account
  end

  def update
    @account = Account.find(params[:id])
    respond_to do |format|
      if @account.update_attributes(account_params)
        format.html { redirect_to @account, notice: 'Account was successfully updated.' }
        format.json { head :no_content } # 204 No Content
      else
        format.html { render action: 'edit' }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def account
    @account ||= accounts.find(params[:id])
  end

  def accounts
    @accounts = current_user.accounts
  end

  def account_params
    params.require(:account).permit(:name, :critical_value, :send_notifications)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :invalidate_simultaneous_user_session,
                unless: proc { |request| request.controller_name == 'sessions' && request.action_name == 'create' }

  def invalidate_simultaneous_user_session
    if current_user && session[:sign_in_token] != current_user.current_sign_in_token
      scope = Devise::Mapping.find_scope!(current_user)
      redirect_path = after_sign_out_path_for(scope)
      Devise.sign_out_all_scopes ? sign_out : sign_out(scope)
      redirect_to redirect_path,
                  alert: 'Your session has been invalidated because you have logged in from somewhere else.'
    end
  end
end

app/controllers/user_logins_controller.rb
class UserLoginsController < ApplicationController
  before_action :authenticate_user!

  def index
    user_logins
  end

  private

  def user_logins
    @user_logins ||= current_user.logins
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :admin_only

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    unless current_user.admin?
      unless @user == current_user
        redirect_to :back, alert: 'Access denied.'
      end
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to users_path, notice: 'User created.'
    else
      redirect_to users_path, alert: 'Unable to create user.'
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(secure_params)
      redirect_to users_path, notice: 'User updated.'
    else
      redirect_to users_path, alert: 'Unable to update user.'
    end
  end

  def destroy
    user = User.find(params[:id])
    user.destroy
    redirect_to users_path, notice: 'User deleted.'
  end

  private

  def admin_only
    unless current_user.admin?
      redirect_to :back, alert: 'Access denied.'
    end
  end

  def secure_params
    params.require(:user).permit(:role)
  end

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/accounts/index.html.erb
<div class="row">
  <div class="col-md-8">
    <h2>Accounts</h2>
    <table class="table">
      <thead>
      <th>Name</th>
      <th>Total</th>
      <th>Critical Value</th>

      <th>Send notification?</th>

      </thead>
      <tbody>
      <% @accounts.each do |account| %>
          <tr>
            <td><%= link_to "#{account.name}", account %></td>
            <td class="<%= account.total > 0 ? 'positive' : (account.total < 0 ? 'negative' : '') %>">
              <strong><%= account.total %></strong></td>
            <td><%= best_in_place account, :critical_value, :as => :input, :classes => 'bounce_on_success', :ok_button => "Confirm", :ok_button_class => "btn btn-primary btn-sm" %>  </td>
            <td><%= best_in_place account, :send_notifications, :as => :select, :collection => {false => "No", true => "Yes"} %>
            </td>
          </tr>
      <% end %>
      </tbody>
    </table>
  </div>
  <div class="col-md-4">
    <h2>Add new Account</h2>
    <%= simple_form_for @account do |f| %>
        <%= f.input :name %>
        <%= f.input :critical_value %>
        <%= f.input :send_notifications, as: :boolean, checked_value: true, unchecked_value: false %>
        <%= f.button :submit ,class: 'btn btn-success'%>
    <% end %>
  </div>
</div>

app/views/accounts/show.html.erb
<div class="row">


  <div class="col-md-8">
    <h2>
      <%= @account.name %>'s transactions
    </h2>

    <h3 class="<%= @account.total > 0 ? 'positive' : (@account.total < 0 ? 'negative' : '') %>">
      Total :  <%= @account.total %>
    </h3>


    <div class="transactions" ng-app="financio" ng-controller="TransactionsCtrl" ng-cloak="true" ng-init="init('<%= @account.id %>')">
      <label>Date from</label>
      <input class="dp" autoclose="true" ng-model="parent.dateFrom" data-provide="datepicker">
      <label>Date to</label>
      <input class="dp" ng-model="parent.dateTo" data-provide="datepicker">
      <button class="btn btn-success" ng-click="loadData()">Load transactions</button>

      <table class="table" ng-table="transactionsTable" show-filter="true">
        <tr ng-repeat="transaction in $data track by $index">
          <td data-title="'#'">
            {{$index+1}}
          </td>
          <td data-title="'Id'" sortable="'id'">
            {{transaction.id}}
          </td>
          <td data-title="'Category'" sortable="'category_name'" filter="{'category_name':'text'}">
            {{transaction.category_name}}
          </td>
          <td ng-class="transaction.value > 0 ? 'positive' : (transaction.value < 0 ? 'negative': '')"data-title="'Value'" sortable="'value'">
            {{transaction.value}}
          </td>
          <td data-title="'Subject'" sortable="'subject'">
            {{transaction.subject}}
          </td>
          <td data-title="'Purpose'" sortable="'purpose'">
            {{transaction.purpose}}
          </td>
          <td data-title="'Date'" sortable="'transaction_date'">
            {{transaction.transaction_date| date : 'MM-dd-yyyy'}}
          </td>
        </tr>

      </table>


    </div>
  </div>
  <div class="col-md-4">
    <%= form_for(@transaction=AccountTransaction.new, :url => account_account_transactions_path(@account, @transaction), :html => {:role => 'form'}) do |f| %>
        <h3>Add new Transaction</h3>

        <div class="form-group">
          <%= f.label :category %>
          <%= f.text_field :category, class: 'form-control', :required => true %>
        </div>
        <div class="form-group">
          <%= f.label :value %>
          <%= f.number_field :value, class: 'form-control', :step => 'any', :required => true %>
        </div>
        <div class="form-group">
          <%= f.label :purpose %>
          <%= f.text_field :purpose, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :subject %>
          <%= f.text_field :subject, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :transaction_date %>
          <%= f.text_field :transaction_date, class: 'dp', :data => {:provide => "datepicker"}, :required => true %>
        </div>

        <%= f.submit 'Add new transaction', :class => 'btn btn-success' %>
    <% end %>
  </div>
</div>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
    <% if msg.is_a?(String) %>
        <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
          <%= content_tag :div, msg, :id => "flash_#{name}" %>
        </div>
    <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">

    <div class="navbar-header">

      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a href="#" class="navbar-brand">Financio</a>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav pull-right">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if user_signed_in? %>
    <li><%= link_to 'Accounts', accounts_path %></li>
    <li><%= link_to "Edit #{current_user.email}", edit_user_registration_path %></li>
    <li><%= link_to 'Account activity', user_activity_path %></li>
    <li><%= link_to 'Sign out', destroy_user_session_path, :method => 'delete' %></li>
<% else %>
    <li><%= link_to 'Sign in', new_user_session_path %></li>
    <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>
<% if user_signed_in? %>
    <% if current_user.admin? %>
        <li><%= link_to 'Users', users_path %></li>
    <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= content_for?(:title) ? yield(:title) : "Financio" %></title>
  <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Financio" %>">
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<header>
  <%= render 'layouts/navigation' %>
</header>
<main role="main">
  <%= render 'layouts/messages' %>
  <%= yield %>
</main>
</body>
</html>

app/views/user_logins/index.html.erb
<div class="container">
  <h2>User Activity</h2>
  <ol>
    <% @user_logins.reverse.each do |login| %>
        <li>
          <p><i class="fa fa-sign-in"></i> You have logged in at <%= login.signed_in_at %></p>

          <p><i class="fa fa-sign-out"></i>
            <% if login.signed_out_at %>
                You have logged out at <%= login.signed_out_at %>
            <% else %>
                This sessions has not been logged out yet
            <% end %>
          </p>
        </li>
    <% end %>
  </ol>
</div>

app/views/users/_user.html.erb
<td>
  <%= link_to user.email, user %>
</td>
<td>
  <%= form_for(user) do |f| %>
      <%= f.select(:role, User.roles.keys.map { |role| [role.titleize, role] }) %>
      <%= f.submit 'Change Role', :class => 'button-xs' %>
  <% end %>
</td>
<td>
  <%= link_to("Delete user", user_path(user), :data => {:confirm => "Are you sure?"}, :method => :delete, :class => 'button-xs') unless user == current_user %>
</td>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users</h3>

    <div class="column">
      <table class="table">
        <tbody>
        <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>

  <div class="authform">
    <%= form_for(@user=User.new, :url => create_user_path(@user), :html => {:role => 'form'}) do |f| %>
        <h3>Create User</h3>

        <div class="form-group">
          <%= f.label :email %>
          <%= f.email_field :email, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :password %>
          <%= f.password_field :password, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :password_confirmation %>
          <%= f.password_field :password_confirmation, class: 'form-control' %>
        </div>
        <%= f.submit 'create', :class => 'button right' %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<h3>User</h3>

<p>Email: <%= @user.email if @user.email %></p>

app/views/visitors/index.html.erb
<h3>Welcome to Financio!</h3>